name:          Code Guide by @mdo, Translated by @SpencerAung
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://code-guide.spenceraung.me

markdown:      rdiscount
permalink:     pretty
pygments:      true